//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndustriaEscuelaDBModelContainer : DbContext
    {
        public IndustriaEscuelaDBModelContainer()
            : base("name=IndustriaEscuelaDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Accion> Acciones { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<CuentaCorriente> CuentasCorrientes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<Insumo> Insumos { get; set; }
        public virtual DbSet<DetalleVenta> DetallesVentas { get; set; }
    }
}
